DEFAULTS = {
    "device": {"name": "PicoController"},
    "leds": {
        "count": 144,
        "pin": 0,
        "on_after_boot": True,
        "segmenting": {"enabled": False, "length": 2},
    },
    "mode": {
        "current": "static",
        "brightness": 50,
        "speed": 10,
        "on": True,
        "color": [255, 120, 30],
        "direction": "forward",
    },
    "modes": {
        "off": {"fade_ms": 600},
        "white": {},
        "static": {},
        "rainbow": {},
        "runner": {"length": 5},
    },
    "wifi": {"ssid": "", "password": ""},
    "mqtt": {
        "server": "",
        "port": 1883,
        "user": "",
        "password": "",
        "base_topic": "controller/led/1",
        "use_single_topic_for_state_update": False,
        "ssl": False,
        "ssl_params": {},
        "ntp_host": "pool.ntp.org",
    },
    "logging": {"enabled": False, "level": "info"},
    "button": {"pin": 3},
    "ir": {"pin": 2},
    "watchdog": {"enabled": False},
}
